apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: corka149/whoami:latest
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 4000
        livenessProbe: 
          httpGet:
            path: /v1/health
            port: 4000
        readinessProbe:
          httpGet:
            path: /v1/ready
            port: 4000
        env:
          - name: OTHER_SERVICE_HOST
            value: http://whoami-service:4000
          - name: ENVIRONMENT_MESSAGE
            value: Greetings stranger!
